### PR TITLE
added accordion style expansion

### PR DESCRIPTION
**Pull request by manolingam**

### CODE REVIEW

**Comment by dekanbro** [comment]
@manolingam do you think you could get this working in the table layout? with out the table we kinda lose the highscore style branding

image

@DarrenRM any other comments?

**Comment by manolingam** [comment]
Sure! Working on @dekanbro

**Comment by manolingam** [comment]
Tried using tables from react bootstrap but couldn't make the accordion work as expected. So I have used *material-UI lists* to make it somehow related to what's needed @dekanbro

**Comment by skuhlmann** [comment]
went with a different solution.

**Pull request closed without merging**
